In [14]:
# data-analysis-basic-kadai
# kadai_003

# NumPyをインポート
import numpy as np

A = np.array([[0, 1],
           [2, 3],
           [4, 5]])

# arange関数で数列を生成し、reshape関数で2×4行列に変換
B = np.arange(8).reshape((2, 4))

print(np.dot(A, B))

# A @ Bでも計算可能。rabel関数で1次元配列に戻して、max関数で最大値を出力
print("最大値:", max((A @ B).ravel()))

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47
